---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit the README.Rmd file -->


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### step 12.2

- Ryan's note: Creating our repository was straightforward and the instructions made it clear.
- Mason's note: Our repository was already created, but I know how to create one my following the instructions.

### step 12.3

- Ryan's note: I had accidentally skipped the git configuration part when creating the R Studio project but it was an easy fix; I have experience with git commands in the terminal.
  
* Ishan's note: I successfully cloned the project from the github repo on RStudio 
on my computer.

- Mason's note: I was able to add a new project in R studio from the git repository. I had previous git experience from other classes, so it took a little longer to figure out the R studio method than to just use the terminal.

### step 12.4

- Ryan's note: Instructions make it clear on how to commit using R Studio, but I think I would rather use git commands in the terminal since I'm already comfortable with that.

* Ishan's note: I wrote this line in RStudio and saved the changes to the md file. 

- Mason's note: this line was written in R studio

### step 12.5

- Ryan's note: Similar to step 12.4, instructions were clear and I had no problems using R Studio's UI to make changes to the remote repository.

* Ishan's note: I pushed my changes many times but didn't see anything on the repo. Update: I was trying to push without comitting, so the repo wasn't updating. 

- Mason's note: I got a commit and push to work at first, though I forgot to knit recently so it wasn't properly updated

### step 12.6

- Ryan's note: Able to see my changes from the previous steps and the message from R Studio in the readme.

* Ishan's note: I can see my changes in the github repo.

- Mason's note: I can see my commits pushed to the remote repo

# Lab report #1

Follow the instructions posted at https://ds202-at-isu.github.io/labs.html for the lab assignment. The work is meant to be finished during the lab time, but you have time until Monday evening to polish things.

Include your answers in this document (Rmd file). Make sure that it knits properly (into the md file). Upload both the Rmd and the md file to your repository.  

All submissions to the github repo will be automatically uploaded for grading once the due date is passed.
Submit a link to your repository on Canvas (only one submission per team) to signal to the instructors that you are done with your submission.
